### ISSUE TITLE
The container version doesn't write files

### ISSUE THREAD

**Issue by msuchane** [redhat-documentation/newdoc#17]
The container (Docker or Podman) package doesn't write files to the host file system. Instead, the containerized `newdoc` generates the file and saves it inside the container, which then immediately exits and the file is lost. Additionally, `newdoc` reports no errors when this happens because from its point of view, everything went well.

The root issue is the configuration of the container packaging. I need to figure out how to write the generated file to the host rather than inside the container.

For now, I'm going to mark this as a known issue in the readme.

**Comment by msuchane** [comment]
## Workaround

To work around the problem, you can start a shell session from the container and copy the generated files between the container and the host. For example, this workaround uses the Podman container platform:

1. Start the `newdoc` container and run its shell:

    ```
    $ podman run -ti --entrypoint=/bin/bash mrksu/newdoc
    ```

2. Inside the container, create the AsciiDoc module:

    ```
    root@c8649a3bd5c8:/# newdoc -c "Module title"
    ```

    The module now exists in the root directory of the running container.

3. Leave the container shell running and switch to another terminal.

4. Find the ID of the running `newdoc` container:

    ```
    $ podman container list
    ```

5. Copy the file from the running container to the host:

    ```
    $ podman cp c8649a3bd5c8:/con_module-title.adoc target-directory
    ```

6. The generated file now exists in `target-directory` on the host system.

Alternatively, build `newdoc` from source.

**Comment by mikemckiernan** [comment]
Wiser advise than mine is available, but I don't think you have an issue.  Bind mounts ought to be acceptable for this utility.

```bash
docker run --rm -it -v $(pwd):/target mrksu/newdoc -p "Restarting the detector" -T /target
```
The result is that the utility creates a file in the current working directory.

```text
‣  File generated: /target/proc_restarting-the-detector.adoc
   include::<path>/proc_restarting-the-detector.adoc[leveloffset=+1]
```
I think you're good. Not a bug.

**Comment by msuchane** [comment]
Mike, thanks for pointing me in the right direction. I still consider it a bug, though, because I'd prefer not having to specify all the command-line options.

Meanwhile, I've found resources in the Docker documentation that should help me improve the behavior of the container and  mount the shared directory by default:

* https://docs.docker.com/storage/volumes/
* https://docs.docker.com/compose/compose-file/compose-file-v3/#volume-configuration-reference
* https://docs.docker.com/engine/reference/builder/#volume
* https://docs.docker.com/storage/bind-mounts/

**Comment by msuchane** [comment]
This issue is now fixed.

I've read up on bind mounts in Docker and adjusted the container configuration. The container now mounts the current working directory from the host to the container.

Some limitations inherent to the container technology still remain, but I think this solution is now usable.

See the documentation: <https://redhat-documentation.github.io/newdoc/#_container>.
