### ISSUE TITLE
ID without a prefix by default

### ISSUE THREAD

**Issue by msuchane** [redhat-documentation/newdoc#21]
According to my recent survey, most people don't want the ID to have a module-type prefix. Let's change the default behavior.

However, the results were extremely close, so the feature must be easily configurable.

Finally, if we want to keep the default prefix in the file name, we need two options: one that configures the filename prefix, and one that configures the ID prefix.

**Comment by msuchane** [comment]
I'm moving the milestone so that I can release the validation feature as soon as it's ready, not blocked by this issue.

**Comment by rkratky** [comment]
+1 to this. I've no idea where the "module prefix in ID" idea came from, but it doesn't seem to make any sense. It would be great to have this configurable. Perhaps splitting the currently available option that allows leaving out the prefixes from the ID and the file name (`--no-prefixes`) would be enough:

* `--no-prefixes-ids`
* `--no-prefixes-files`

Or something similar.

**Comment by mjahoda** [comment]
Because IDs are also in URLs, I wouldn't consider having unnecessary con, proc, and ref prefixes harmless, and I'm also supporting the removal from templates and changing the newdoc defaults. If there is a chance to speed up the things, I can submit a PR for the templates part.

**Comment by msuchane** [comment]
The changes are now ready and on review in #34.
