### ISSUE TITLE
Validation:  XML markup examples in AsciiDoc files cause errors

### ISSUE THREAD

**Issue by inoxx03** [redhat-documentation/newdoc#25]
Our docs set features numerous examples of XML markup.
Some of the XML tag pairs within these examples seem to trigger validation failures for the modules that contain them.

The following code block is taken from the [`proc-producing-native-executable.adoc`](https://gitlab.cee.redhat.com/quarkus-documentation/quarkus/-/raw/main/modules/proc-producing-native-executable.adoc) module file.
Line 18 referenced in the newdoc validation error output (2nd example) contains the  `<id>native</id>` tag pair.

```asciidoc
[source,xml]
----
<profiles>
    <profile>
        <id>native</id> 
        <properties>
            <quarkus.package.type>native</quarkus.package.type>
        </properties>
    </profile>
</profiles>
----
```

Attempting to validate the file using `newdoc -l proc-producing-native-executable.adoc` produces the following false-positive error:

```
💾 File: proc-producing-native-executable.adoc
    🔶 Warning: The module is missing the module type variable.
    🔴 Error at line 18: The file seems to contain HTML markup
```

This is not a serious issue, unless newdoc validation is used in a CI pipeline, where it could trigger a build pipeline failure due to the source content not passing an initial validation check.

**Comment by msuchane** [comment]
Yes, this is a limitation of the way that `newdoc` tries to detect HTML. It just looks for a pair of pointy-bracket tags that are on the same line. Specifically, this is the regular expression:

```
<[[:alpha:]]+>.*</[[:alpha:]]+>
```

In code blocks like the one in your example, tags tend to be spread over several lines, which doesn't trigger the regular expression. In comparison, actual HTML code in a paragraph should usually be on one line.

I can think of a couple solutions to improve the HTML detection and limit false positives:

* Try to parse code block delimiters. Look for tags only outside the code blocks. This would bring us closer to reimplementing `asciidoctor` in `newdoc`, which might eventually be inevitable.
* Detect just certain predefined HTML tags that are likely to appear in paragraphs, like `<b>`. This would still lead to false positives if a code block includes HTML, or false negatives if some of the predefined tags are also valid XML.

Anyway, I'll consider this a bug and I'll fix it in a future release.

**Comment by VladimirSlavik** [comment]
How likely is it that people will use inline html to tweak the output? I can understand how one could get that idea, but IMO it's highly unlikely.

> This would bring us closer to reimplementing asciidoctor in newdoc, which might eventually be inevitable.

Been there, done that. Welcome to the club!

**Comment by msuchane** [comment]
> How likely is it that people will use inline html to tweak the output? I can understand how one could get that idea, but IMO it's highly unlikely.

I don't think I've ever seen a case like that in RHEL 8 documentation, so I'd say very unlikely. Regardless, Patheon 2 requires that there's no HTML markup, and a validator needs to make sure that's the case.

> Been there, done that. Welcome to the club!

Any tips? :-)

**Comment by VladimirSlavik** [comment]
> Any tips? :-)

If you have to reinvent the wheel, at least enjoy the opportunity.

**Comment by inoxx03** [comment]
> Yes, this is a limitation of the way that `newdoc` tries to detect HTML. It just looks for a pair of pointy-bracket tags that are on the same line.

Figures, seeing that single tags are not triggering the error, whereas inline tag pairs do.
Introducing an "unsafe" option to ignore the pattern match would defeat the purpose of the validator, too :/
 
> Try to parse code block delimiters. Look for tags only outside the code blocks. This would bring us closer to reimplementing asciidoctor in newdoc, which might eventually be inevitable.

Sounds good on paper, but it's probably massively dirty work to implement something like this :/

> Detect just certain predefined HTML tags that are likely to appear in paragraphs, like <b>. This would still lead to false positives if a code block includes HTML, or false negatives if some of the predefined tags are also valid XML.

Exactly. Given the variety of XML tags the validator could encounter, their overlap with valid HTML might be considerable.
Even when ignoring a specific tag set (such as the one used in Maven's `pom.xml` format) the reliability could be unpredictable at best .

> How likely is it that people will use inline html to tweak the output? I can understand how one could get that idea, but IMO it's highly unlikely.

I second that this is not very likely in any of our product docs. The closest I've seen to this is an occasional HTML character code used to substitute a non-breaking hyphen and such.

Anyway, thank you for planning to address this:)

**Comment by msuchane** [comment]
The newdoc validation is now deprecated in favor of the enki tool, so I'm closing this issue.
