### ISSUE TITLE
Validation of global attr value used in plain text

### ISSUE THREAD

**Issue by soulcharmer** [redhat-documentation/newdoc#28]
Considering upstream docs reuse of our files, all attributes defined in the global attribute file should be used consistently.

Consequently, if one of such values is used in a source file in plain text, it creates a hard-to-detect inconsistency when reusing content from downstream to upstream or vice versa.

This RFE is to expand newdoc validation to find such plain-text occurrences of tokens that could and should be replaced by a global attribute.

For example, for an attribute like

:ProductName: {RH} Enterprise{nbsp}Linux

there might be several variants using character attributes, other attributes, or no attributes at all.

**Comment by msuchane** [comment]
The newdoc validation is now deprecated in favor of the enki tool, so I'm closing this issue.
