### ISSUE TITLE
An option to simplify the templates for community

### ISSUE THREAD

**Issue by msuchane** [redhat-documentation/newdoc#31]
Many elements in the current templates are workarounds for various issues in the Red Hat publishing workflow. These elements are primarily the ifdefs and the different forms of the context attribute.

For community projects that deploy their documentation in a much simpler configuration, such as without any nesting of assemblies, newdoc should provide an option that strips the templates of these unnecessary elements.

**Comment by msuchane** [comment]
To preserve at least the idea of context so that you can optionally use it when needed, we can save some instructions in a comment next to the ID.

**Comment by msuchane** [comment]
This template simplification also provides one solution to the problem in https://github.com/redhat-documentation/modular-docs/issues/220

**Comment by msuchane** [comment]
The option is now available in newdoc version 2.16.0. You can generate files with with the `--simplified`, `-S` option to remove the context attribute.

**Comment by msuchane** [comment]
Hi @Lennonka,

If I remember this right, you were interested in simplified modular templates for Foreman/Satellite community docs using newdoc, right? That was back in December 2021 and this idea fell through the cracks, sorry. I've revived it now because it also seems increasingly useful for RHEL and other projects.

If it's still of use to you, feel free to test the `--simplified`, `-S` option with newdoc.

**Comment by Lennonka** [comment]
Actually, we could use more force on the simplification. For example, in our upstream, we want our modules to start with the ID and avoid module metadata:

```diff
- :_newdoc-version: 2.16.0
- :_template-generated: 2024-02-08
- 
- :_mod-docs-content-type: CONCEPT
- 
 [id="test"]
 = Test
 
- [role="_abstract"]
 ...
```

**Comment by Lennonka** [comment]
We do use the other roles, though.
