### ISSUE TITLE
Changelog file

### ISSUE THREAD

**Issue by mmuehlfeldRH** [redhat-documentation/newdoc#32]
Can you please add a changelog file to the repo, and also let the RPM install it to /usr/share/doc/newdoc/ ?

Background: Today dnf installed a newdoc update to 2.9.8. I wanted to check what's new, but on GitHub, the latest version under "Releases" is still 2.9.6. A continuously updated changelog file in the repo would be helpful.

**Comment by msuchane** [comment]
Hi Marc,

Unfortunately, the releases page requires me to enter the release information manually. I missed the last two releases there, but after your report, I added them:

<https://github.com/redhat-documentation/newdoc/releases>

Having a separate changelog file is probably a good idea, as well as installing it. Users could view the changelog file without opening GitHub, such as when they clone the repository. I'm all for it.

Installing the file using the RPM will be somewhat more difficult, though. So far, I've been using a packaging solution that makes it hard or impossible to install anything besides the main newdoc binary. I'm reading the official Fedora packaging guide now, and hopefully, I can learn the proper packaging workflow there.

**Comment by VladimirSlavik** [comment]
@msuchane if you want, I could probably show you how to release automatically with github actions...

**Comment by msuchane** [comment]
Thanks for the offer, @VladimirSlavik, that sounds like it could be pretty useful.

What I'm struggling with the most, though, is RPM packaging itself. I've tried several times, but all RPM packaging guides are... impenetrable, and Rust RPM documentation in particular is nonexistent. It feels like packaging Rust applications as RPM is tribal knowledge of a selected few.

Do you have any pointers in that direction?

**Comment by VladimirSlavik** [comment]
I don't have more than names, unfortunately, but that might be a start? I'll contact you in some more private medium.

**Comment by jhradilek** [comment]
I just ran `rpm -ql newdoc` to look for the ChangeLog file after seeing that `dnf` pulled in the new version and was disappointed not to see it. So @mmuehlfeldRH is definitely not the only one with this use case.

**Comment by msuchane** [comment]
Hi @jhradilek, that's right, unfortunately the changelog still isn't packaged with newdoc. The best I can give you is this online version:

https://github.com/redhat-documentation/newdoc/blob/main/CHANGELOG.md

I welcome anybody who's more familiar with RPM packaging than me to help me figure out how to add more files to [the RPM spec configuration](https://github.com/redhat-documentation/newdoc/blob/main/.rpm/newdoc.spec).

**Comment by msuchane** [comment]
With the current RPM configuration, the changelog as well as the readme and a man page are available from the RPM package.

I'm closing this issue.
