### ISSUE TITLE
[RFE] Allowlist for chars in filenames to prevent illegal chars in uclude statements

### ISSUE THREAD

**Issue by soulcharmer** [redhat-documentation/newdoc#33]
Recently, we got a filename into an include statement by accident that evaded newdoc's sanitization by using a weird Unicode apostrophe:

include::modules/security/proc_changing-a-user’s-clearance-level-within-the-defined-security-range-in-mls.adoc[leveloffset=+1] 

it broke preview links in an MR

The RFE is to consider a limited allowlist of characters to be used in file names that will not clash with subsequent include statements.

**Comment by soulcharmer** [comment]
[Marek] Note to self: use string.is_ascii() here

**Comment by msuchane** [comment]
This is now fixed in the 2.10.2 release. The module ID now replaces all non-ASCII characters with dashes.
