### ISSUE TITLE
Document `-l`/`--validate` as deprecated

### ISSUE THREAD

**Issue by jhradilek** [redhat-documentation/newdoc#36]
In the official [CHANGELOG](https://github.com/redhat-documentation/newdoc/blob/main/CHANGELOG.md#v2130), the entry for version 2.12.0 states that the `--validate`/`-l` option is deprecated. This information is also displayed as a warning when you attempt to use this option. There is, however, no indication that this option is deprecated in the built-in help which is what the majority of users is likely to read:

```
$ newdoc --version
Version: 2.13.0
$ newdoc --help
Generate pre-populated module files formatted with AsciiDoc that are used in Red Hat and Fedora
documentation.

Usage: newdoc -a TITLE... -c TITLE... -p TITLE... -r TITLE... -s TITLE... [-i TITLE] -l FILE... [-M]
[-E] [-P] [-A] [-T DIRECTORY] [-v | -q]

Available options:
  Generate or validate files:
[...]
    -l, --validate <FILE>  Validate (lint) an existing module or assembly file
[...]
```

Could you please add this information?

**Comment by msuchane** [comment]
Thanks for the tip. This is now fixed in version 2.13.1.
