### ISSUE TITLE
Update the 

### ISSUE THREAD

**Issue by jhradilek** [redhat-documentation/newdoc#37]
In reaction to [issue 203](https://github.com/redhat-documentation/modular-docs/issues/203), the [modular-docs](https://github.com/redhat-documentation/modular-docs) project has recently [changed the name of the attribute that uniquely identifies the module type](https://github.com/redhat-documentation/modular-docs/pull/209/files) from `_content-type` to `_mod-docs-content-type`. I believe `newdoc` should update its templates to reflect this change.

**Comment by msuchane** [comment]
I've just released `newdoc` version 2.14.1 with the renamed attribute.

The new version will be available shortly from the RPM repository and other sources.
