### ISSUE TITLE
Change date format of _template-generated attribute to YYYY-MM-DD

### ISSUE THREAD

**Issue by mmuehlfeldRH** [redhat-documentation/newdoc#39]
`newdoc` 2.15.0 adds an `_template-generated` attribute to the files, but the value uses single digits for the month and day:

```
:_template-generated: 2023-2-7
```

I recommend to change the date format to the more common YYYY-MM-DD format.

**Comment by msuchane** [comment]
Fixed in version 2.15.1 and released.

Thanks for reporting the bug! It was easy to miss when I developed the date format after 2023-12-10 😄
