### ISSUE TITLE
Simplify harder for community docs

### ISSUE THREAD

**Issue by Lennonka** [redhat-documentation/newdoc#45]
We could use more force on the simplification in TheForeman upstream.
Specifically, we want our modules to start with the ID and avoid module metadata, i.e. `_*` attributes:

```patch
- :_newdoc-version: 2.16.0
- :_template-generated: 2024-02-08
- 
- :_mod-docs-content-type: CONCEPT
- 
 [id="test"]
 = Test
 ```
I hope it would be okay to not include this metadata when the `-S` option is used.

**Comment by msuchane** [comment]
This is now resolved with newdoc version 2.18.0.

You can now use the following options:

* `--metadata`
* `--no-metadata` or `-D`
* `metadata = bool` in configuration files
