### ISSUE TITLE
GitHub releases does not match tags

### ISSUE THREAD

**Issue by maximiliankolb** [redhat-documentation/newdoc#46]
Hi all,

* latest release on GitHub: **2.14.0** https://github.com/redhat-documentation/newdoc/releases
* latest tag on GitHub: **2.17.0** https://github.com/redhat-documentation/newdoc/tags

I see two solutions: either drop the "releases" feature on GitHub for the project; or think about creating releases based on tags.

just FYI: I have installed newdoc via `cargo install newdoc --version 2.17.0` which works fine.

**Comment by mmuehlfeldRH** [comment]
I added the latest version (2.18.3) to the GitHub releases page.

By the way, if you run Fedora, RHEL, CentOS stream, or OpenSUSE Tumbleweed, you can use the [Copr repository](https://copr.fedorainfracloud.org/coprs/mmuehlfeldrh/newdoc-rs/) to stay up to date.
